apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world 
        image: quay.io/chris_ricci/hello-world-instrumented:v1
        ports:
        - name: web
          containerPort: 5000
        - name: metrics
          containerPort: 8000
