apiVersion: v1
kind: Service
metadata:
  name: prometheus-hello-world
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 30901
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-hello-world
